# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20180817_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='headache',
            name='answer1',
            field=models.CharField(default=b'yes', max_length=200),
        ),
        migrations.AddField(
            model_name='headache',
            name='answer2',
            field=models.CharField(default=b'no', max_length=200),
        ),
        migrations.AddField(
            model_name='stomach',
            name='answer1',
            field=models.CharField(default=b'yes', max_length=200),
        ),
        migrations.AddField(
            model_name='stomach',
            name='answer2',
            field=models.CharField(default=b'no', max_length=200),
        ),
    ]
