# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0006_auto_20180817_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='headache',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='stomach',
        ),
    ]
