# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0008_disease_question_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Disease',
            new_name='question',
        ),
    ]
